version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: auth-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=authentication
      - NODE_ENV=development
    volumes:
        - ./:/usr/src/app
    command: yarn start

  postgres:
    image: postgres
    container_name: auth-postgres
    ports:
        - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=authentication
      - POSTGRES_PASSWORD=secret

volumes:
  postgres:
    driver: local